// The Composite Portrait — the flagship paid SKU of the tests funnel
// (docs/tests-monetization.md §4, §6, §8): one six-chapter report built from
// the intersections of every test the account has completed. The portrait
// belongs to the ACCOUNT, not a session — the caller's JWT is the authority
// here, unlike the other funnels where a bare session UUID is the capability.
//
// Money flow mirrors the quiz/photo reports: cache → gate → spend → generate
// → cache. The idempotency key is portrait:{user_id}:{sha256 of the sorted
// participating session ids} — the same composition is never charged twice
// (both languages and retries ride one spend), while a newly completed test or
// a retake changes the composition and honestly opens a new purchase.
//
// Э7 exit criterion (§6): every participating session is re-scored here from
// its raw answers — stored client-computed outcome/scale_totals are never
// trusted in a paid operation. The recomputed numbers are written back so the
// data self-heals, and only then summed (once) into the cross-test scale layer.
import Anthropic from "npm:@anthropic-ai/sdk";
import { createClient } from "npm:@supabase/supabase-js@2";
import { CREDIT_COSTS } from "../_shared/credits-config.ts";
import { normalizeScaleTotals, scoreTest } from "../../../src/tests/engine.ts";
import type { PsychTest, ScaleTotals, TestAnswers, TestOutcome } from "../../../src/tests/types.ts";
import attachmentStyles from "../../../src/content/tests/attachment_styles_v1.json" with { type: "json" };
import boundariesPeoplePleasing from "../../../src/content/tests/boundaries_people_pleasing.json" with { type: "json" };
import burnoutDiagnostic from "../../../src/content/tests/burnout_diagnostic_v1.json" with { type: "json" };
import digitalDetox from "../../../src/content/tests/digital_detox_test.json" with { type: "json" };
import emotionalIntelligence from "../../../src/content/tests/emotional_intelligence.json" with { type: "json" };
import fomoSocialComparison from "../../../src/content/tests/fomo_social_comparison_v1.json" with { type: "json" };
import friendshipPsychology from "../../../src/content/tests/friendship_psychology_v1.json" with { type: "json" };
import friendshipRedFlags from "../../../src/content/tests/friendship_red_flags_v1.json" with { type: "json" };
import imposterSyndrome from "../../../src/content/tests/imposter_syndrome.json" with { type: "json" };
import ipipBigFive from "../../../src/content/tests/ipip_big_five.json" with { type: "json" };
import loveLanguages from "../../../src/content/tests/love_languages_v1.json" with { type: "json" };
import relationshipCompatibility from "../../../src/content/tests/relationship_compatibility_v1.json" with { type: "json" };
import romanticPotential from "../../../src/content/tests/romantic_potential_v1.json" with { type: "json" };
import selfConfidenceMultiscale from "../../../src/content/tests/self_confidence_multiscale_v1.json" with { type: "json" };
import sixteenTypes from "../../../src/content/tests/sixteen_types.json" with { type: "json" };
import socialBattery from "../../../src/content/tests/social_battery_v1.json" with { type: "json" };
import textConflict from "../../../src/content/tests/text_conflict_communication.json" with { type: "json" };
import toxicPatterns from "../../../src/content/tests/toxic_patterns.json" with { type: "json" };
import valuesPriorities from "../../../src/content/tests/values_priorities_v1.json" with { type: "json" };
import catalogue from "../../../src/content/tests/index.json" with { type: "json" };

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const REPORT_MODEL = "claude-sonnet-5";

/** Gate (§4): the portrait exists from three completed tests up. */
const PORTRAIT_GATE = 3;

// Synced with src/tests/engine.ts (tests-generate-report imports it from
// there; this bundle carries its own copy). The DB column default stays 1 on
// purpose: rows written without an explicit version read as "old" and heal
// upward on the next paid recompute — never the other way around.
const ENGINE_VERSION = 2;

type Lang = "en" | "ru";

// All seven launch tests ride statically in the bundle (~660 KB together —
// comfortably inside limits, §6), unlike the SPA where each is its own chunk.
// The JSON is generated by tools/tests-import/to-canonical.mjs, which validates
// its shape; TypeScript only ever sees it as arbitrary JSON (same cast as the
// SPA's registry).
const TESTS: Record<string, PsychTest> = {};
for (const raw of [
  attachmentStyles,
  boundariesPeoplePleasing,
  burnoutDiagnostic,
  digitalDetox,
  emotionalIntelligence,
  fomoSocialComparison,
  friendshipPsychology,
  friendshipRedFlags,
  imposterSyndrome,
  ipipBigFive,
  loveLanguages,
  relationshipCompatibility,
  romanticPotential,
  selfConfidenceMultiscale,
  sixteenTypes,
  socialBattery,
  textConflict,
  toxicPatterns,
  valuesPriorities,
]) {
  const test = raw as unknown as PsychTest;
  TESTS[test.id] = test;
}

const CATALOGUE = catalogue as unknown as Array<{ id: string; title: Record<Lang, string> }>;

const CHAPTER_KEYS = ["frame", "throughlines", "interplay", "weak_link", "in_action", "missing"] as const;

// §4: six chapters, ~800-1000 words total. Keys are stable ids — the app owns
// the localized chapter titles; the model writes only body text.
const PORTRAIT_SCHEMA = {
  type: "object",
  properties: {
    frame: {
      type: "string",
      description:
        "Chapter 'The overall frame': who this person is by the sum of their tests — the portrait's thesis, the 2-3 traits everything else hangs on. 2-3 short paragraphs separated by blank lines, ~170 words",
    },
    throughlines: {
      type: "string",
      description:
        "Chapter 'Throughlines': 3-4 scales that run across several tests, each traced through the tests it appears in — and at least one genuine contradiction (a high scale colliding with a low one, or one scale reading differently in different tests) named precisely. ~230 words",
    },
    interplay: {
      type: "string",
      description:
        "Chapter 'How it works together': how traits from DIFFERENT tests amplify or compensate each other in real life — pairs and their visible effect, not a list of scores. ~180 words",
    },
    weak_link: {
      type: "string",
      description:
        "Chapter 'The weak link': the one place this combination is most likely to cost them — where it breaks under load, said plainly and kindly. 1-2 paragraphs, ~130 words",
    },
    in_action: {
      type: "string",
      description:
        "Chapter 'The portrait in action': 3 concrete moves tailored to this exact combination — each starts from a trait the portrait named, not generic advice. ~150 words",
    },
    missing: {
      type: "string",
      description:
        "Chapter 'What's missing': which of the untaken tests would sharpen this portrait and what exactly each would clarify about the picture so far — a bridge, not an ad. When tests_not_taken is empty, say instead what a retake in a few months could show about how this portrait shifts. One paragraph, ~90 words",
    },
  },
  required: ["frame", "throughlines", "interplay", "weak_link", "in_action", "missing"],
  additionalProperties: false,
} as const;

const SYSTEM_BASE = `You write "The Composite Portrait" — the flagship six-chapter report of Looplore, a pop-psychology self-reflection product (entertainment and self-knowledge, not therapy). The reader has completed several of Looplore's psychological tests. You are given aggregates only: each test's resulting profile with its factor percentages, and the cross-test scale layer — the 0-100 score each psychological scale earned across ALL tests taken, with per-test values where a scale lives in two or more tests.

This is the one report no single test could produce: its material is the intersections. Build the portrait primarily from cross_test_scales — especially collisions: a high scale against a low one, or the same scale reading differently in different tests. A contradiction named precisely is worth more than three smooth generalizations.

Rules: never invent facts beyond the data given; you have no raw answers, so never quote or paraphrase "what they answered". Refer to tests by the human names given in the data, never by ids. Scale and factor ids are readable English (self_esteem, empathy) — render them as natural words of the output language, never print snake_case. Use numbers sparingly, as evidence, not decoration. No clinical jargon, no diagnosis, no therapy-speak, no toxic positivity; if the data points somewhere heavy, say it plainly and kindly — behavior and its price, not a verdict.

Voice: warm but unsentimental, precise, a little literary — a perceptive friend who has read all their results side by side. Second person throughout. ~800-1000 words across the six chapters. Plain text only: paragraphs separated by blank lines, no markdown, no headings inside chapters (the app renders chapter titles itself). Never mention being an AI.`;

const LANG_SUFFIX: Record<Lang, string> = {
  en: "\n\nWrite all six chapters in English.",
  ru: "\n\nВсе шесть глав напиши по-русски, на «ты». Пиши как сильный русский автор поп-психологии, а не как переводчик: короткие фразы, живой разговорный ритм, никакого канцелярита, причастных цепочек и дословных калек с английского. Названия тестов и профилей бери русские из данных; названия шкал переводи естественными русскими словами.",
};

interface StoredOutcome {
  factorPercentages?: Record<string, number>;
  profileId?: string | null;
  typeCode?: string;
}

interface SessionRow {
  id: string;
  test_id: string;
  answers: TestAnswers;
  outcome: StoredOutcome | null;
  completed_at: string;
}

const secretCache = new Map<string, string>();

async function getSecret(
  admin: ReturnType<typeof createClient>,
  name: string,
): Promise<string | null> {
  const cached = secretCache.get(name);
  if (cached) return cached;
  const envValue = Deno.env.get(name);
  if (envValue) {
    secretCache.set(name, envValue);
    return envValue;
  }
  const { data, error } = await admin.rpc("unloop_get_secret", { secret_name: name });
  if (error || typeof data !== "string" || !data) return null;
  secretCache.set(name, data);
  return data;
}

async function sha256Hex(input: string): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(input));
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

function isCompletePortrait(value: unknown): value is Record<(typeof CHAPTER_KEYS)[number], string> {
  return (
    typeof value === "object" &&
    value !== null &&
    CHAPTER_KEYS.every((key) => typeof (value as Record<string, unknown>)[key] === "string")
  );
}

/**
 * §6: recomputation vs stored client result, compared on profileId and factor
 * percentages with rounding tolerance (both sides round to one decimal, so a
 * real difference is at least a full tenth). A divergence is either engine
 * drift after weight edits (expected, healed by the writeback) or a forged
 * client result (interesting as a signal).
 */
function outcomeDiverges(stored: StoredOutcome, fresh: TestOutcome): boolean {
  if ((stored.profileId ?? null) !== fresh.profileId) return true;
  if ((stored.typeCode ?? null) !== (fresh.typeCode ?? null)) return true;
  const factorIds = new Set([
    ...Object.keys(stored.factorPercentages ?? {}),
    ...Object.keys(fresh.factorPercentages),
  ]);
  for (const id of factorIds) {
    const a = Number(stored.factorPercentages?.[id] ?? NaN);
    const b = fresh.factorPercentages[id] ?? NaN;
    if (!Number.isFinite(a) || !Number.isFinite(b) || Math.abs(a - b) > 0.11) return true;
  }
  return false;
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS });
  const json = (body: unknown, status = 200) =>
    new Response(JSON.stringify(body), {
      status,
      headers: { ...CORS, "Content-Type": "application/json" },
    });

  try {
    // The only input is the language — the composition is derived server-side
    // from the account's sessions, so an empty body simply means English.
    const body = await req.json().catch(() => ({}));
    const lang: Lang = body?.lang === "ru" ? "ru" : "en";

    const admin = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );

    // Credits-only SKU: there is no legacy boolean payment for the portrait.
    const enabled = ((await getSecret(admin, "CREDITS_ENABLED")) ?? "").toLowerCase() === "true";
    if (!enabled) return json({ error: "credits_disabled" }, 503);

    // The portrait belongs to the account (§8): the caller's JWT names the
    // owner. The anon key resolves to no user — a portrait needs an account.
    const auth = req.headers.get("authorization") ?? "";
    const jwt = auth.startsWith("Bearer ") ? auth.slice(7) : "";
    const { data: userData } = jwt ? await admin.auth.getUser(jwt) : { data: { user: null } };
    const userId = userData?.user?.id ?? null;
    if (!userId) return json({ error: "sign_in_required" }, 401);

    // Latest completed session per test — the same distinct-on semantics as
    // looplore_test_scale_profile, but through the service role and with the
    // raw answers the recomputation needs.
    const { data: rows, error: rowsError } = await admin
      .from("looplore_test_sessions")
      .select("id, test_id, answers, outcome, completed_at")
      .eq("user_id", userId)
      .not("completed_at", "is", null)
      .order("completed_at", { ascending: false });
    if (rowsError) {
      console.error("tests-portrait sessions", rowsError);
      return json({ error: "internal" }, 500);
    }

    const latest = new Map<string, SessionRow>();
    for (const row of rows ?? []) {
      // Only sessions the engine can honestly re-score count toward the
      // portrait: a known test and a non-empty answer map. Anything else is
      // unusable for a paid recomputation (§6) — skipped, never trusted.
      if (latest.has(row.test_id) || !(row.test_id in TESTS)) continue;
      if (
        !row.answers ||
        typeof row.answers !== "object" ||
        Array.isArray(row.answers) ||
        Object.keys(row.answers).length === 0
      ) {
        continue;
      }
      latest.set(row.test_id, row as SessionRow);
    }

    const sessions = [...latest.values()];
    if (sessions.length < PORTRAIT_GATE) {
      return json({ error: "gate", completed: sessions.length, required: PORTRAIT_GATE }, 403);
    }

    // Composition key: the sorted participating session ids. The same set
    // yields the same hash — cached portrait, duplicate (free) spend; a new
    // test or a retake changes the set and starts a fresh purchase. No
    // language in the key: both languages of one composition share one spend.
    const setHash = await sha256Hex(sessions.map((s) => s.id).sort().join("+"));

    const testsMeta = sessions
      .map((s) => ({ test_id: s.test_id, completed_at: s.completed_at }))
      .sort((a, b) => (a.completed_at < b.completed_at ? 1 : -1));

    // Cache: looplore_portraits, created by the А1 tests-monetization
    // migration (unique on user_id + set_hash). A cached language is already
    // paid for — serve it without touching the ledger or the session rows.
    const { data: cacheRow } = await admin
      .from("looplore_portraits")
      .select("report, created_at")
      .eq("user_id", userId)
      .eq("set_hash", setHash)
      .maybeSingle();
    const cachedPortrait = (cacheRow?.report as Record<string, unknown> | null)?.[lang];
    if (isCompletePortrait(cachedPortrait)) {
      return json({
        portrait: cachedPortrait,
        tests: testsMeta,
        set_hash: setHash,
        created_at: cacheRow?.created_at ?? null,
        cached: true,
      });
    }

    // §6: re-score every session from raw answers and write the result back —
    // outcome, scale_totals and engine_version self-heal on every paid
    // operation. The writeback is best-effort: a failed update is logged and
    // must not block a paid portrait.
    const recomputed: Array<{ session: SessionRow; outcome: TestOutcome }> = [];
    for (const session of sessions) {
      const outcome = scoreTest(TESTS[session.test_id], session.answers);

      if (session.outcome && outcomeDiverges(session.outcome, outcome)) {
        // §6 wants divergence visible; the function log is where server-side
        // signals live (PostHog capture stays client-side in this codebase).
        console.log(
          "test_outcome_mismatch",
          JSON.stringify({
            session_id: session.id,
            test_id: session.test_id,
            stored_profile: session.outcome.profileId ?? null,
            recomputed_profile: outcome.profileId,
          }),
        );
      }

      const { error: writebackError } = await admin
        .from("looplore_test_sessions")
        .update({
          outcome: {
            factorPercentages: outcome.factorPercentages,
            scaleScores: outcome.scaleScores,
            profileId: outcome.profileId,
            ...(outcome.typeCode ? { typeCode: outcome.typeCode } : {}),
          },
          scale_totals: outcome.scaleTotals,
          engine_version: ENGINE_VERSION,
          updated_at: new Date().toISOString(),
        })
        .eq("id", session.id);
      if (writebackError) console.error("tests-portrait writeback", session.id, writebackError);

      recomputed.push({ session, outcome });
    }

    // Sum the recomputed sufficient statistics across tests, normalize ONCE —
    // the same arithmetic as looplore_test_scale_profile, but over verified
    // numbers (§6). Per-test normalized values are kept alongside so the
    // prompt can show how one scale reads in different tests.
    const combinedTotals: ScaleTotals = {};
    const perTestScores = new Map<string, Record<string, number>>();
    for (const { session, outcome } of recomputed) {
      for (const [scale, [weighted, maxWeighted]] of Object.entries(outcome.scaleTotals)) {
        const prev = combinedTotals[scale] ?? [0, 0];
        combinedTotals[scale] = [prev[0] + weighted, prev[1] + maxWeighted];
        let byTest = perTestScores.get(scale);
        if (!byTest) {
          byTest = {};
          perTestScores.set(scale, byTest);
        }
        byTest[session.test_id] = outcome.scaleScores[scale] ?? 0;
      }
    }
    const combinedScores = normalizeScaleTotals(combinedTotals);

    // Prompt aggregates (§4): per-test profile + factor percentages + type
    // code, cross-test scales with per-test values (scales living in 2+ tests
    // are the portrait's core), a few loud single-test scales, and the untaken
    // tests for the closing bridge. Raw answers stay out — 15K+ tokens of
    // noise the recomputation has already digested.
    const titleOf = (testId: string) => TESTS[testId].title[lang];

    const testsPayload = recomputed.map(({ session, outcome }) => {
      const test = TESTS[session.test_id];
      const profile = outcome.profileId ? test.profiles[outcome.profileId] : undefined;
      return {
        test: test.title[lang],
        profile: profile?.name[lang] ?? null,
        profile_id: outcome.profileId,
        ...(outcome.typeCode ? { type_code: outcome.typeCode } : {}),
        factor_percentages: Object.fromEntries(
          Object.entries(outcome.factorPercentages).map(([id, pct]) => [
            test.factorNames[id]?.[lang] ?? id,
            pct,
          ]),
        ),
        taken_on: session.completed_at.slice(0, 10),
      };
    });

    const sharedScales = [...perTestScores.entries()]
      .filter(([, byTest]) => Object.keys(byTest).length >= 2)
      .map(([scale, byTest]) => ({
        scale,
        score: combinedScores[scale] ?? 0,
        by_test: Object.fromEntries(
          Object.entries(byTest).map(([testId, value]) => [titleOf(testId), value]),
        ),
      }))
      .sort((a, b) => Math.abs(b.score - 50) - Math.abs(a.score - 50))
      .slice(0, 18);

    const singles = [...perTestScores.entries()]
      .filter(([, byTest]) => Object.keys(byTest).length === 1)
      .map(([scale, byTest]) => ({
        scale,
        score: combinedScores[scale] ?? 0,
        test: titleOf(Object.keys(byTest)[0]),
      }))
      .sort((a, b) => b.score - a.score);
    // Top and bottom four, deduped when fewer than eight singles exist.
    const notableSingles = [
      ...new Map([...singles.slice(0, 4), ...singles.slice(-4)].map((s) => [s.scale, s])).values(),
    ];

    const takenIds = new Set(recomputed.map(({ session }) => session.test_id));
    const testsNotTaken = CATALOGUE.filter((t) => !takenIds.has(t.id)).map((t) => t.title[lang]);

    const portraitInput = {
      tests_taken: testsPayload,
      cross_test_scales: sharedScales,
      notable_single_test_scales: notableSingles,
      tests_not_taken: testsNotTaken,
    };

    // Spend after the cache miss, before generation. The idempotency key makes
    // client retries, a crash between spend and cache write, and the second
    // language all free (duplicate spends return ok without a new debit).
    const spend = await admin.rpc("credits_spend", {
      p_user_id: userId,
      p_amount: CREDIT_COSTS.portrait,
      p_kind: "spend_portrait",
      p_key: `portrait:${userId}:${setHash}`,
      p_ref: setHash,
      p_meta: null,
    });
    if (spend.error || spend.data?.ok !== true) {
      const balance = typeof spend.data?.balance === "number" ? spend.data.balance : 0;
      return json({ error: "payment_required", balance }, 402);
    }

    const apiKey = await getSecret(admin, "ANTHROPIC_API_KEY");
    if (!apiKey) return json({ error: "llm_not_configured" }, 500);
    const anthropic = new Anthropic({ apiKey });

    const response = await anthropic.messages.create({
      model: REPORT_MODEL,
      // Six chapters at 800-1000 words; RU runs well over EN in tokens.
      max_tokens: 4000,
      // Left on, thinking would share the budget with the chapters and can
      // truncate the JSON (same reasoning as the other sonnet calls).
      thinking: { type: "disabled" },
      system: SYSTEM_BASE + LANG_SUFFIX[lang],
      output_config: { format: { type: "json_schema", schema: PORTRAIT_SCHEMA } },
      messages: [
        {
          role: "user",
          content: `Write the six chapters of the composite portrait for this person:\n${JSON.stringify(portraitInput, null, 2)}`,
        },
      ],
    });

    if (response.stop_reason === "refusal") {
      return json({ error: "generation_declined" }, 500);
    }
    const textBlock = response.content.find((b: { type: string }) => b.type === "text");
    if (!textBlock) return json({ error: "empty_response" }, 500);
    const portrait = JSON.parse((textBlock as { text: string }).text);

    // Both languages of one composition live in one row. The spend already
    // landed — a failed cache write must not eat the portrait; the next call
    // simply regenerates for free on the duplicate key.
    const mergedReport = { ...((cacheRow?.report as Record<string, unknown>) ?? {}), [lang]: portrait };
    const { error: saveError } = await admin
      .from("looplore_portraits")
      .upsert(
        { user_id: userId, set_hash: setHash, report: mergedReport, engine_version: ENGINE_VERSION },
        { onConflict: "user_id,set_hash" },
      );
    if (saveError) console.error("tests-portrait save", saveError);

    return json({
      portrait,
      tests: testsMeta,
      set_hash: setHash,
      created_at: cacheRow?.created_at ?? new Date().toISOString(),
      cached: false,
    });
  } catch (err) {
    console.error("tests-portrait error", err);
    return json({ error: "internal" }, 500);
  }
});
