/**
 * Test catalogue and loader.
 *
 * The seven launch tests weigh ~660 KB of JSON together, so only the catalogue
 * is imported eagerly — each test itself arrives through a dynamic import and
 * becomes its own chunk.
 */

import catalogue from "../content/tests/index.json";
import type { Localized, PsychTest } from "./types";

export interface TestSummary {
  id: string;
  title: Localized;
  description: Localized;
  categoryId: string;
  estimatedMinutes: number;
  questionCount: number;
}

export const TEST_CATALOGUE = catalogue as TestSummary[];

/**
 * Static map rather than a template literal import, so the bundler can see
 * every target and split them properly.
 */
const LOADERS: Record<string, () => Promise<{ default: unknown }>> = {
  attachment_styles_v1: () => import("../content/tests/attachment_styles_v1.json"),
  boundaries_people_pleasing: () => import("../content/tests/boundaries_people_pleasing.json"),
  burnout_diagnostic_v1: () => import("../content/tests/burnout_diagnostic_v1.json"),
  digital_detox_test: () => import("../content/tests/digital_detox_test.json"),
  fomo_social_comparison_v1: () => import("../content/tests/fomo_social_comparison_v1.json"),
  friendship_psychology_v1: () => import("../content/tests/friendship_psychology_v1.json"),
  friendship_red_flags_v1: () => import("../content/tests/friendship_red_flags_v1.json"),
  imposter_syndrome: () => import("../content/tests/imposter_syndrome.json"),
  ipip_big_five: () => import("../content/tests/ipip_big_five.json"),
  love_languages_v1: () => import("../content/tests/love_languages_v1.json"),
  relationship_compatibility_v1: () => import("../content/tests/relationship_compatibility_v1.json"),
  romantic_potential_v1: () => import("../content/tests/romantic_potential_v1.json"),
  sixteen_types: () => import("../content/tests/sixteen_types.json"),
  social_battery_v1: () => import("../content/tests/social_battery_v1.json"),
  text_conflict_communication: () => import("../content/tests/text_conflict_communication.json"),
  toxic_patterns: () => import("../content/tests/toxic_patterns.json"),
  values_priorities_v1: () => import("../content/tests/values_priorities_v1.json"),
};

const cache = new Map<string, PsychTest>();

export async function loadTest(id: string): Promise<PsychTest> {
  const cached = cache.get(id);
  if (cached) return cached;

  const loader = LOADERS[id];
  if (!loader) throw new Error(`Unknown test: ${id}`);

  const module = await loader();
  // The JSON is generated by tools/tests-import/to-canonical.mjs, which validates
  // its shape; TypeScript only ever sees it as arbitrary JSON.
  const test = module.default as PsychTest;
  cache.set(id, test);
  return test;
}
