#!/usr/bin/env node
/**
 * K1a invariant: the editorial catalogue layer and the generated catalogue
 * must describe the same set of tests.
 *
 *   node tools/tests-audit/catalogue-meta.mjs
 *
 * `src/tests/merchandising.json` is authored by hand while
 * `src/content/tests/index.json` is generated by the import pipeline, so the
 * two drift the moment a batch lands without its editorial pass. The visible
 * symptom would be mild and easy to miss — a test that no router answer ever
 * surfaces, sitting silently at the bottom of its shelf — which is exactly the
 * kind of thing a blocking check is for.
 *
 * Runs in CI alongside the other tests:* invariants.
 */

import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "../..");
const load = (p) => JSON.parse(fs.readFileSync(path.join(ROOT, p), "utf8"));

const catalogue = load("src/content/tests/index.json");
const merch = load("src/tests/merchandising.json");

/**
 * Mirrors the unions in merchandising.ts. Duplicated deliberately: this script
 * cannot import the TypeScript, and a silent typo in a theme name would
 * otherwise only surface as an empty browse page in K1b.
 */
const INTENTS = new Set(["relationships", "friends", "self", "energy", "habits", "work"]);
const THEMES = new Set([
  "attachment",
  "communication",
  "conflict",
  "boundaries",
  "friendship",
  "personality",
  "emotions",
  "confidence",
  "energy",
  "focus",
  "values",
]);

const errors = [];

const catalogueIds = catalogue.map((t) => t.id);
const merchIds = Object.keys(merch);

for (const id of catalogueIds) {
  if (!merch[id]) {
    errors.push(`${id}: в каталоге есть, в merchandising.json нет — тест не попадёт ни в один ответ роутера`);
  }
}
for (const id of merchIds) {
  if (!catalogueIds.includes(id)) {
    errors.push(`${id}: в merchandising.json есть, в каталоге нет — осиротевшая запись`);
  }
}

for (const [id, entry] of Object.entries(merch)) {
  if (!Array.isArray(entry.intents) || entry.intents.length === 0) {
    errors.push(`${id}: intents пуст — тест невидим для «Начни отсюда»`);
  }
  if (!Array.isArray(entry.themes) || entry.themes.length === 0) {
    errors.push(`${id}: themes пуст — тест не попадёт на тематические страницы K1b`);
  }
  for (const i of entry.intents ?? []) {
    if (!INTENTS.has(i)) errors.push(`${id}: неизвестный intent "${i}"`);
  }
  for (const t of entry.themes ?? []) {
    if (!THEMES.has(t)) errors.push(`${id}: неизвестная theme "${t}"`);
  }
}

// Every intent must have somewhere to send people: an answer that resolves to
// nothing is a dead end on the first screen a visitor sees.
for (const intent of INTENTS) {
  const covered = Object.values(merch).some((e) => (e.intents ?? []).includes(intent));
  if (!covered) errors.push(`intent "${intent}": ни одного теста — ответ роутера ведёт в пустоту`);
}

if (errors.length) {
  console.error(`catalogue-meta: ${errors.length} ошибк(и)`);
  for (const e of errors) console.error(`  ✗ ${e}`);
  process.exit(1);
}

const themeCounts = {};
for (const entry of Object.values(merch)) {
  for (const t of entry.themes) themeCounts[t] = (themeCounts[t] ?? 0) + 1;
}
const emptyThemes = [...THEMES].filter((t) => !themeCounts[t]);

console.log(`catalogue-meta: ${catalogueIds.length} тестов, все размечены; тем в работе ${Object.keys(themeCounts).length}/${THEMES.size}`);
if (emptyThemes.length) {
  // Not an error: a theme may be declared ahead of the batch that fills it.
  console.log(`  темы без тестов (K1b пропустит): ${emptyThemes.join(", ")}`);
}
